-- Schema and seed data for demo_db
CREATE TABLE IF NOT EXISTS items (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL
);

INSERT INTO items (name) VALUES
('apple'),
('apricot'),
('avocado'),
('banana'),
('bilberry'),
('blackberry'),
('blackcurrant'),
('blueberry'),
('boysenberry'),
('breadfruit'),
('cantaloupe'),
('carambola'),
('cherimoya'),
('cherry'),
('clementine'),
('cloudberry'),
('coconut'),
('cranberry'),
('currant'),
('date'),
('dragonfruit'),
('durian'),
('elderberry'),
('feijoa'),
('fig'),
('goji berry'),
('gooseberry'),
('grape'),
('grapefruit'),
('guava'),
('honeydew'),
('jackfruit'),
('jabuticaba'),
('jujube'),
('kiwi'),
('kumquat'),
('langsat'),
('lemon'),
('lime'),
('longan'),
('loquat'),
('lychee'),
('mandarin'),
('mango'),
('mangosteen'),
('marionberry'),
('melon'),
('mulberry'),
('nectarine'),
('olive'),
('orange'),
('papaya'),
('passionfruit'),
('peach'),
('pear'),
('persimmon'),
('pineapple'),
('plantain'),
('plum'),
('pluot'),
('pomegranate'),
('pomelo'),
('quince'),
('rambutan'),
('raspberry'),
('redcurrant'),
('salak'),
('satsuma'),
('serviceberry'),
('starfruit'),
('strawberry'),
('tamarillo'),
('tamarind'),
('tangerine'),
('tayberry'),
('ugli fruit'),
('white currant'),
('yuzu'),
('youngberry'),
('ackee'),
('araça'),
('buddhas hand'),
('cacoa'),
('canistel'),
('capuli'),
('damson'),
('dewberry'),
('eggfruit'),
('gac'),
('genip'),
('grumichama'),
('hog plum'),
('ilama'),
('jaboticaba'),
('kakadu plum'),
('lucuma'),
('mabolo'),
('miracle fruit'),
('nance'),
('surinam cherry');
